data_analyst_task:
  description: >
    Phân tích câu hỏi "{question}".
     - Dựa vào nguồn kiến thức của bạn về cấu trúc dữ liệu và bảng trong hệ thống quản lý tài liệu hãy lựa chọn nguồn dữ liệu và công cụ phù hợp để truy xuất thông tin cần thiết.
     - Trình bày câu trả lời một cách rõ ràng, đầy đủ và dễ hiểu cho người dùng.
  expected_output: >
    Một câu trả lời ngắn gọn, chính xác, phản ánh đúng trọng tâm câu hỏi và được diễn giải dễ hiểu.
  agent: data_analyst_agent
